### ISSUE TITLE
An example to make the case for paper

### ISSUE THREAD

**Issue by manish211** [SoftwareEngineeringToolDemos/Paper#12]
Adding this point thinking that this may make the case for the paper stronger.

Some tools are not well maintained and have version dependencies. Many times not well documented as well. This gives rise to groups such as below. Lack of documentation increases dependencies on people leading to communication overheads as well.

Request you to browse through the conversation in this link:

https://groups.google.com/forum/#!msg/java-pathfinder/nvGJ3qb9bK0/xv0TA5XXBgAJ

Have a look at the below response.
Steven Lauterburg  
11/18/15

jpf-actor does not work with the latest version of jpf-core (**one of these days I will have to rectify that**).  You can, however, access a snapshot of an older jpf-core version that it will work with at http://babelfish.arc.nasa.gov/trac/jpf/wiki/projects/jpf-core .  Scroll to the bottom of the screen and expand the attachments tab.  jpf-actor will work with jpf-core-r1038-src.zip

-Steve Lauterburg
- show quoted text -

**Comment by CaptainEmerson** [comment]
I think dependency versioning is just one technical issue out of many that we might call out as problem. Looking through the survey of "what went wrong," dependencies and versioning do seem to be a common theme. But is there some reason that we think this is particularly bad with research tools, rather than software in general?

As the paper states in before the results, I'm avoiding calling out any particular tool about versioning issues.

**Comment by manish211** [comment]
Okay. For "But is there some reason that we think this is particularly bad with research tools, rather than software in general?", I see most of the problems related to poor versioning and documentation overlap with research tools and software. I am not able to think of anything except that if software is written within an organization, there is some sense of accountability. If something is brought to the notice of developer, it is more likely to get fixed. However, with respect to research tools, nobody is obliged to fix something that was missing. It is likely that tools which are related to published papers may be the least priority activity as indicated by this example. So the misery is more likely to continue for people who want to use it. I may be wrong since I do not have a very clear understanding of the hierarchy system in research. Just sharing my perspective.

**Comment by manish211** [comment]
closing
