### ISSUE TITLE
Paper Outcome

### ISSUE THREAD

**Issue by chbrown13** [SoftwareEngineeringToolDemos/Paper#27]
Hi @CaptainEmerson, was this paper ever published anywhere?

**Comment by CaptainEmerson** [comment]
Hi Chris! It was not. We got a rejection from TSE. Happy to send you the reviews if you like and you can decide if you'd like to do something further with it?

**Comment by chbrown13** [comment]
Ah ok, was thinking of this as related work for a different project---but might be interested in doing something further with it/reading the reviews. Do you have plans to revive it?

**Comment by CaptainEmerson** [comment]
No plans on my end. If you don't want to try to publish this paper, you can also cite it as a not-peer-reviewed github paper/project.

**Comment by chbrown13** [comment]
Thanks!
