### ISSUE TITLE
Fix Author List

### ISSUE THREAD

**Issue by CaptainEmerson** [SoftwareEngineeringToolDemos/Paper#3]
Right now, it's in a \thanks command (with a discouraged \IEEEoverridecommandlockouts command). Instead, authors should be more like this:

```
\author{\IEEEauthorblockN{Emerson Murphy-Hill, Shabbir Abdul, Varun Aettapu} %add all authors here!
\IEEEauthorblockA{Department of Computer Science\\
North Carolina State University\\
Raleigh, North Carolina, USA\\
emerson@csc.ncsu.edu,\{sabdul,vaettap]}@ncsu.edu}%add all emails here!
```

This isn't a hard change to make, but it'll take a few minutes to do manually.

**Comment by bhanuanand28** [comment]
Committed to Master with the changes....
